### ISSUE TITLE
pyautogui.press('w') doesn't work in game 

### ISSUE THREAD

**Issue by dedarh** [Minish144/lost-ark-fishing-bot#1]
pyautogui.press('w'), игра не реагирует на эмуляция нажатия клавиши

**Comment by Minish144** [comment]
> pyautogui.press('w'), игра не реагирует на эмуляция нажатия клавиши

привет! нужно запускать ide или командную строку от имени администратора

**Comment by dedarh** [comment]
Ok thanks. Can you please write me message in VK (vk.com/dedarh)?
