### ISSUE TITLE
No module named win32gui

### ISSUE THREAD

**Issue by Tianyu9207** [Minish144/lost-ark-fishing-bot#2]
Привет, я новичок в python, сталкнулся с такой проблемой, когда запускаю прогу.

C:\Users\Tianyu9207\Downloads\lost-ark-fishing-bot-master\lost-ark-fishing-bot-master>python main.py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    import win32gui
ModuleNotFoundError: No module named 'win32gui'

pyautogui,cv2 и numpy я установил успешно.
Даже скачал версию 3.7.3. Я попробовал установить версию x64 и 32. 
Версия windows 10, 64.
я попробовал вбить pip install win32gui, выдает в конце ошибку:
Command "c:\users\tianyu9207\appdata\local\programs\python\python37-32\python.exe c:\users\tianyu9207\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py get_requires_for_build_wheel C:\Users\TIANYU~1\AppData\Local\Temp\tmpsnv4yu8m" failed with error code 1 in C:\Users\TIANYU~1\AppData\Local\Temp\pip-install-dg2wc9ui\win32gui

Прошу Вашей помощи! Спасибо!

**Comment by Tianyu9207** [comment]
решил проблему через команду pip install pywin32. Прогу запустил, но все равно не работает, может это связано с тем, что скрин не правильно берет/читает? Я непонял, как правильно подогнать этот скрин

**Comment by enigma110** [comment]
Так, я смог запустить - Система Win10 x64
из дополнительного поставил pip install pywin32 
Работает, но 7-я строчку я закоментил, оно работает  
Но если кто-то появится перед персонажем(прошмыгнёт) - не захочет работать дальше и запустить его нужно первый раз нажав W 
Спасибо за скрипт
PS вернул строчку на место, есть один промах при рыбалки - если рыба сверху к крючку подплывает, скрипт её за поплавок воспринимает и подсекает(можно скинуть на чел. фактор нажатия)  А вот маячение перед персонажем осталась - рекомендую рыбачить в Загорье южнее голубятни(если продолжить спускаться дальше после семян)
