### ISSUE TITLE
5 минут работы

### ISSUE THREAD

**Issue by mmm69** [Minish144/lost-ark-fishing-bot#3]
А у кого-то он дольше работает ?

проблема ,что он раньше  пытается закинуть, чем  откатилось умение.

Можно добавить условие, если персонаж тупо стоит без поплавка  определенное время надо его кидать.

**Comment by Minish144** [comment]
> А у кого-то он дольше работает ?
> 
> проблема ,что он раньше пытается закинуть, чем откатилось умение.
> 
> Можно добавить условие, если персонаж тупо стоит без поплавка определенное время надо его кидать.

он плохо работает это правда, но времени его допиливать у меня сейчас нет
и, если честно, желания тоже
