### ISSUE TITLE
Готов заплатить если допилишь бота

### ISSUE THREAD

**Issue by ggrey57** [Minish144/lost-ark-fishing-bot#4]
Привет я готов тебе заплатить если допилишь бота сделаешь ловлю сеткой. Будь человеком сделай сетку

**Comment by dedarh** [comment]
@ggrey57  я доделал ловлей сеткой )

**Comment by Minish144** [comment]
> Привет я готов тебе заплатить если допилишь бота сделаешь ловлю сеткой. Будь человеком сделай сетку

лестно, конечно) но мне сейчас совсем не до этого, спасибо)
