### ISSUE TITLE
Doesn't work any more?

### ISSUE THREAD

**Issue by kgorin8** [Minish144/lost-ark-fishing-bot#5]
Hey. I tried your method also there's apparently pyautogui.locateOnScreen that does image finding much more convenient. Unfortunately as of right now the game doesn't accept input from scripts? Or am I missing something?

**Comment by Minish144** [comment]
> Hey. I tried your method also there's apparently pyautogui.locateOnScreen that does image finding much more convenient. Unfortunately as of right now the game doesn't accept input from scripts? Or am I missing something?

Hey! It got nerfed recently. Yes, it doesnt work anymore, unfortunately.
